[alias]
# Building
c = "clippy"
br = "build --release"
rr = "run --release"
nt = "nextest run"
w = "watch -c"
# Packages
up = "update"
ft = "feature"
tr = "tree"
ls = "tree --depth 1"
pkgup = "install-update -a"
# Cleaning
cl = "clean"
cr = "clean-recursive"
cc = "cache -a"

[build]
rustflags = ["-C", "link-arg=-fuse-ld=mold"]
