[alias]
# Building
c = "clippy"
br = "build --release"
rr = "run --release"
nt = "nextest run"
# Packages
ft = "feature"
tr = "tree"
pkgup = "install-update -a"
# Cleaning
cl = "clean"
cr = "clean-recursive"
cc = "cache -a"

[build]
rustc-wrapper = "sccache"
rustflags = ["-C", "link-arg=-fuse-ld=mold"]
