[alias]
br = "lbuild --release"
rr = "lrun --release"
pkgup = "install-update -a"
feat = "feature"
b = "lbuild"
r = "lrun"
c = "lcheck"
t = "ltest"

[build]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]
