[alias]
br = "build --release"
rr = "run --release"
pkgup = "install-update -a"
nt = "nextest run"
c = "clippy"
cl = "clean"
cc = "cache -a"
cr = "clean-recursive"

# [build]
# rustc-wrapper = "/home/i32/.cargo/bin/sccache"
# rustflags = ["-C", "link-arg=-fuse-ld=lld"]
