#!/bin/sh

super + p; c
    rofi -show calc

XF86AudioMute
    pamixer -t && notify-send "Volume Toggled (Muted: $(pamixer --get-mute))"
XF86AudioLowerVolume
    pamixer -u && pamixer -d 5 && notify-send "Volume Decreased ($(pamixer --get-volume))"
XF86AudioRaiseVolume
    pamixer -u && pamixer -i 5 && notify-send "Volume Increased ($(pamixer --get-volume))"

shift + XF86AudioLowerVolume
    brightnessctl s 10%-
shift + XF86AudioRaiseVolume
    brightnessctl s 10%+

super + F10
    pamixer -t && notify-send "Volume Toggled (Muted: $(pamixer --get-mute))"
super + F11
    pamixer -u && pamixer -d 5 && notify-send "Volume Decreased ($(pamixer --get-volume))"
super + F12
    pamixer -u && pamixer -i 5 && notify-send "Volume Increased ($(pamixer --get-volume))"
