#!/bin/sh

super + b
    firefox
        
super + shift + b
    firefox --private-window

super + shift + d
    Discord

XF86AudioMute
    pamixer -t && notify-send "Volume Toggled (Muted: $(pamixer --get-mute))"
XF86AudioLowerVolume
    pamixer -u && pamixer -d 5 && notify-send "Volume Decreased ($(pamixer --get-volume))"
XF86AudioRaiseVolume
    pamixer -u && pamixer -i 5 && notify-send "Volume Increased ($(pamixer --get-volume))"

shift + XF86AudioLowerVolume
    brightnessctl s 10%-
shift + XF86AudioRaiseVolume
    brightnessctl s 10%+

Print
    maim -s | xclip -selection clipboard -t image/png -i

shift + Print
    maim | xclip -selection clipboard -t image/png -i