#!/bin/sh

super + b
    firefox
        
super + shift + b
    firefox --private-window

super + o
    obsidian

super + shift + d
    Discord

super + shift + f
    Thunar

XF86AudioMute
    pamixer -t
XF86AudioLowerVolume
    pamixer -u && pamixer -d 5
XF86AudioRaiseVolume
    pamixer -u && pamixer -i 5

shift + XF86AudioLowerVolume
    brightnessctl s 10%-
shift + XF86AudioRaiseVolume
    brightnessctl s 10%+

Print
    maim -s | xclip -selection clipboard -t image/png -i

shift + Print
    maim | xclip -selection clipboard -t image/png -i
