#!/bin/sh

# riverctl map normal Super Return spawn "foot"
riverctl map normal Super Return spawn "wezterm start fish"
riverctl map normal Super B spawn "firefox"
riverctl map normal Super O spawn "obsidian"
riverctl map normal Super P spawn "bemenu-run -i -p run --fn 'JetBrainsMono Nerd Font 11' -H 30 --ch 16 --cw 2 --hp 8 --tb '#61afef' --tf '#282c34' --ff '#c8ccd4' --fb '#1e222a' --nb '#282c34' --nf '#61afef' --hb '#61afef' --hf '#282c34' --ab '#282c34' --af '#61afef' --scrollbar autohide"
riverctl map normal Super+Shift A spawn "aseprite"
riverctl map normal Super+Shift B spawn "firefox --private-window"
riverctl map normal Super+Shift D spawn "discord"
riverctl map normal Super+Shift F spawn "figma-linux"
riverctl map normal Super+Shift I spawn "idea-community"
riverctl map normal Super+Shift V spawn "code"
riverctl map normal Super+Shift Y spawn "pycharm-community"
riverctl map normal Super+Shift Z spawn "zotero"

riverctl map normal Super C close
riverctl map normal Super+Shift Q exit
riverctl map normal Super Q spawn "~/.local/bin/power-bemenu.sh"

riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous
riverctl map normal Super BackSpace zoom

riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"
riverctl map normal Super I send-layout-cmd rivertile "main-count +1"
riverctl map normal Super D send-layout-cmd rivertile "main-count -1"

riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt J move down 100
riverctl map normal Super+Alt K move up 100
riverctl map normal Super+Alt L move right 100

riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control J snap down
riverctl map normal Super+Alt+Control K snap up
riverctl map normal Super+Alt+Control L snap right

riverctl map normal Super+Alt+Shift H resize horizontal -100
riverctl map normal Super+Alt+Shift J resize vertical 100
riverctl map normal Super+Alt+Shift K resize vertical -100
riverctl map normal Super+Alt+Shift L resize horizontal 100

riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

for i in $(seq 1 9); do
	tags=$((1 << ($i - 1)))
	riverctl map normal Super $i set-focused-tags $tags
	riverctl map normal Super+Shift $i set-view-tags $tags
	riverctl map normal Super+Control $i toggle-focused-tags $tags
	riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

riverctl map normal Super F toggle-float
riverctl map normal Super Space toggle-fullscreen

riverctl map normal None Print spawn 'grim -g "$(slurp)" - | wl-copy'
riverctl map normal Shift Print spawn 'grim -c - | wl-copy'
riverctl map normal Control Print spawn "grim -g \"\$(slurp -p)\" -t ppm - | convert - -format '%[pixel:p{0,0}]' txt:- | wl-copy"

riverctl declare-mode passthrough
riverctl map normal Super F11 enter-mode passthrough
riverctl map passthrough Super F11 enter-mode normal

riverctl background-color 0x1e222a
riverctl border-color-focused 0x61afef
riverctl border-color-unfocused 0x282c34
riverctl border-color-urgent 0xe06c75
riverctl border-width 2

riverctl set-repeat 25 300
riverctl focus-follows-cursor normal
riverctl set-cursor-warp on-output-change

riverctl default-layout rivertile
rivertile -view-padding 5 -outer-padding 5 -main-ratio 0.5 &

for mode in normal locked; do
	riverctl map $mode None XF86Eject spawn 'eject -T'

	riverctl map $mode None XF86AudioRaiseVolume spawn 'pamixer -i 5'
	riverctl map $mode None XF86AudioLowerVolume spawn 'pamixer -d 5'
	riverctl map $mode None XF86AudioMute spawn 'pamixer --toggle-mute'

	riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
	riverctl map $mode None XF86AudioPlay spawn 'playerctl play-pause'
	riverctl map $mode None XF86AudioPrev spawn 'playerctl previous'
	riverctl map $mode None XF86AudioNext spawn 'playerctl next'

	riverctl map $mode None XF86MonBrightnessUp spawn 'light -A 5'
	riverctl map $mode None XF86MonBrightnessDown spawn 'light -U 5'
done

dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river &

wlr-randr --output eDP-1 --preferred --pos 1920,0
wlr-randr --output HDMI-A-1 --mode 1920x1080@74.973Hz --pos 0,0

waybar &
wbg ~/Pictures/wall/cube.jpg &
