#!/bin/sh

super + p; p
    dm-hub
super + p; e
    dm-confedit
super + p; c
    rofi -show calc
super + p; q
    dm-logout
super + p; m
    dm-man
super + p; k
    dm-kill
super + p; s
    dm-websearch
super + p; f
    fd . $HOME | rofi -keep-right -dmenu -i -p FILES -multi-select | xargs -I {} xdg-open {}
super + p; i
    dm-ip
super + p; n
    dm-note
super + p; y
    dm-youtube

XF86AudioMute
    pamixer -t && notify-send "Volume Toggled (Muted: $(pamixer --get-mute))"
XF86AudioLowerVolume
    pamixer -u && pamixer -d 5 && notify-send "Volume Decreased ($(pamixer --get-volume))"
XF86AudioRaiseVolume
    pamixer -u && pamixer -i 5 && notify-send "Volume Increased ($(pamixer --get-volume))"

super + F10
    pamixer -t && notify-send "Volume Toggled (Muted: $(pamixer --get-mute))"
super + F11
    pamixer -u && pamixer -d 5 && notify-send "Volume Decreased ($(pamixer --get-volume))"
super + F12
    pamixer -u && pamixer -i 5 && notify-send "Volume Increased ($(pamixer --get-volume))"
